package com.example.jstyle.util

object BundleKeys {
    const val dashboardTab = "DASHBOARD_TAB"

    const val flowType = "FLOW_TYPE"
    const val viewType = "VIEW_TYPE"
    const val webType = "WEB_TYPE"
    const val success = "SUCCESS"
    const val failed = "FAILED"
    const val selectedQuestion = "SELECTED_QUESTION"
    const val mobileNo = "MOBILE_NO"
    const val merchants = "MERCHANTS"
    const val category = "CATEGORY"
    const val voucherId = "VOUCHER_ID"
    const val voucherCode = "VOUCHER_CODE"
    const val expirydate = "EXPIRY_DATE"
    const val poolId = "POOL_ID"
    const val giftLock = "GIFT_LOCK"
    const val voucherType = "VOUCHER_TYPE"
    const val voucherName = "VOUCHER_NAME"
    const val filterCategory = "FILTER_CATEGORY"
    const val imageUrl = "IMAGE_URL"
    const val merchantName = "MERCHANT_NAME"
    const val about = "ABOUT"
    const val iconUrl = "ICON_URL"
    const val creditCard = "CREDIT_CARD"
    const val title = "TITLE"
    const val email = "EMAIL"
    const val nric = "NRIC"
    const val passport = "PASSPORT"
    const val blCard = "BL_CARD"
    const val blCardList = "BL_CARD_LIST"
    const val hasInstantCard = "HAS_INSTANT_CARD"
    const val hasMultipleCard = "HAS_MULTIPLE_CARD"
    const val hasOldPin = "HAS_OLD_PIN"
    const val pin = "PIN"
    const val totalCard = "TOTAL_CARD"
    const val screenNumber = "SCREEN_NAME"
    const val referralSuccess = "REFERRAL_SUCCESS"
    const val myVoucher = "MY_VOUCHER"
    const val transactionType = "TRANSACTION_TYPE"
    const val transactionId = "TRANSACTION_ID"
    const val recipients = "RECIPIENTS"
    const val collectedPointsTransaction = "COLLECTED_POINTS_TRANSACTION"
    const val usedPointsTransaction = "USED_POINTS_TRANSACTIrON"
    const val creditCardId = "CREDIT_CARD_ID"
    const val merchantId = "MERCHANT_ID"
    const val creditcardlist = "CREDIT_CARD_LIST"
    const val outletId = "OUTLET_ID"
    const val isKeyInAmount = "IS_KEY_IN_AMOUNT"
    const val isDonation = "IS_DONATION"
    const val isVoucherPayment = "IS_VOUCHER_PAYMENT"
    const val isRefundPayment = "IS_REFUND_PAYMENT"
    const val paymentUrl = "PAYMENT_URL"
    const val scanMerchant = "SCAN_MERCHANT"
    const val merchantTransaction = "MERCHANT_TRANSACTION"
    const val vouchers = "VOUCHERS"
    const val trxId = "trxId" // Transaction Id
    const val trxType = "trxType" // Transaction Type
    const val referralCode = "referralcode"
    const val shareMessage = "sharemobile"
    const val shareLink = "sharelink"
    const val isProfileFlow = "IS_PROFILE_FLOW"
    const val isPartnerLink = "IS_PARTNER_LINK"
    const val hasRegistered = "hasRegistered"
    const val onlyTransfer = "ONLY_TRANSFER"
    const val product = "PRODUCT"
    const val container = "CONTAINER"
    const val transferMethod = "TRANSFER_METHOD"
    const val isWalk = "IS_WALK"

    const val LIST_OF_EXPIRATION = "LIST_OF_EXPIRATIONS"
    const val profileData = "PROFILE_DATA"
    const val addresses = "ADDRESSES"
    const val address = "ADDRESS"
    const val geocoder_latitude = "GEOCODER_LATITUDE"
    const val geocoder_longitude = "GEOCODER_LONGITUDE"
    const val deliveryAddressId = "DELIVERY_ADDRESS_ID"
    const val addressesPosition = "ADDITIONAL_ADDRESS_POSITION"

    const val POINT_TRANSACTION_TAB = "POINT_TRANSACTION_TYPE"
    const val language = "LANGUAGE"
    const val gender = "GENDER"
    const val race = "RACE"
    const val date = "DATE"
    const val maritalStatus = "MARITAL_STATUS"
    const val occupation = "OCCUPATION"
    const val dob = "DOB"
    const val WALLET_TRANSACTION_TAB = "WALLET_TRANSACTION_TYPE"
    const val GIFT_TAB = "GIFT_TAB"

    const val voucherTransaction = "VOUCHER_TRANSACTION"
    const val donationTransaction = "DONATION_TRANSACTION"
    const val cashbackTransaction = "CASHBACK_TRANSACTION"
    const val transaction = "TRANSACTION"
    const val location = "LOCATION"

    const val refundTransactionName = "REFUND_TRANSACTION_NAME"
    const val refundPaidAmount = "REFUND_PAID_AMOUNT"
    const val refundPointsAmount = "REFUND_POINTS_AMOUNT"

    const val generalQuestions = "GENERAL_QUESTIONS"
    const val participatingOutlets = "PARTICIPATING_OUTLETS"
    const val promotions = "PROMOTIONS"
    const val GIFT_QR_CODE = "GIFT_QR_CODE"
    const val GIFT_SHARES = "GIFT_SHARES"
    const val VOUCHER_NUMBER = "VOUCHER_NUMBER"
    const val VOUCHER_QR_CODE = "VOUCHER_QR_CODE"
    const val URL = "URL"

    const val NOTIFICATION_TYPE = "NOTIFICATION_TYPE"
    const val NOTIFICATION_ID = "NOTIFICATION_ID"
    const val NOTIFICATION_DATA = "NOTIFICATION_DATA"

    const val questionId = "QUESTION_ID"
    const val paymentDetails = "PAYMENT_DETAILS"
    const val qrCode = "QR_CODE"
    const val barCode = "BAR_CODE"

    const val kickSession = "KICK_SESSION"

    const val firebaseScreenName = "FIREBASE_SCREEN_NAME"
    const val deeplink = "DEEP_LINK"

    const val IS_PARTNER_OUTLETS: String = "partner_outlet"

    // AppSettings Keys :
    const val POINT_TRANS_THRESHOLD = "pointtransthreshold"
    const val OTP_RESEND_DURATION = "otp.resendduration"
    const val PAYMENT_TRANS_THRESHOLD = "paymenttransthreshold"
    const val OTP_LOCK_TIME = "otp.locktime"
    const val OTP_TRIAL_COUNT = "otp.trialcount"
    const val REG_MAX_CARD_MERGE = "reg.maxcardmerge"
    const val QR_SHARING_DURATION = "qrsharingduration"
    const val MAX_EMAIL_ADD = "maxemailadd"
    const val PIN_TRIAL_COUNT = "pin.trialcount"
    const val VOUCHER_NEARBY_DISTANCE = "voucher.nearbydistance"
    const val VOUCHER_PAGE_SIZE = "voucher.pagesize"
    const val MERCHANT_OTP_RESEND_DURATION = "merchant_otp.resendduration"
    const val MERCHANT_OTP_ATTEMPT_COUNT = "merchant_otp.attemptcount"
    const val HELP_CENTER_PHONE = "helpcenterphone"
    const val HELP_CENTER_EMAIL = "helpcenteremail"
    const val MERCHANT_MAX_DISTANCE = "merchant.maxdistance"
    const val GIFTING_DURATION = "gifting.duration"
    const val PROMOTION_PAGE_SIZE = "promotion.pagesize"
    const val MERCHANT_PAGE_SIZE = "merchant.pagesize"
    const val REFERRAL_PREFIX = "referral.prefix"
    const val REFERRAL_LENGTH = "referral.length"
    const val IPAY88NON3D_LIMIT = "ipay88non3D.limit"
    const val MERCHANT_SEND_REPORT_DURATION = "merchant.sendreport.duration"
    const val MERCHANT_ISSUE_POINT_MAX = "merchant.issuepoint.max"
    const val MERCHANT_TUTORIAL_URL = "merchant.tutorial.url"
    const val MERCHANT_HELP_CENTER_PHONE = "merchant.helpcenter.phone"
    const val MERCHANT_NOTIFICATION_DURATION = "merchant.notification.duration"
    const val REWARD_SIGN_UP_DURATION = "reward.signup.duration"
    const val REWARD_BIRTHDAY_DURATION = "reward.birthday.duration"
    const val REWARD_BIRTHDAY_DAYS_FROM_BIRTHDAY = "reward.birthday.daysfrombirthday"
    const val REG_TRIAL_COUNT = "reg.trialcount"
    const val MERCHANT_OUTLET_DETAIL_PAGE_SIZE = "merchant.outletdetail.pagesize"
    const val MERCHANT_FIND_TRANSACTION_PAGE_SIZE = "merchant.findtransaction.pagesize"
    const val MERCHANT_NOTIFICATION_PAGE_SIZE = "merchant.notification.pagesize"
    const val STATE_MODIFIED_DATE = "state.modifieddate"
    const val REFERRAL_ON = "referral.on"
    const val SELECTED_POOL_ID = "selected_pool_id"

    const val BACK_TO_DASHBOARD = "backtodashboard"
    // end of AppSettings Keys
}